FIX for the following inconsistency observed with real data stream which escaped the multi-threaded unit test    (This was due to not re-checking existing value during write-locked put operation after the allocBlock is called    i.e. if the existing value happened to be in the segment that has just been recycled, the pointer to the previous    value would not know about this, resulting in an attempt to dealloc now invalid block)
    java.lang.ArrayIndexOutOfBoundsException: 3359648 + 4 > 4
    at org.apache.donut.utils.logmap.GrowableByteBuffer.getInt(GrowableByteBuffer.scala:60)
    at org.apache.donut.utils.logmap.IntIndex.get(IntIndex.scala:39)
    at org.apache.donut.utils.logmap.SegmentDirectMemoryLZ4.sizeOf(SegmentDirectMemoryLZ4.scala:174)
    at org.apache.donut.utils.logmap.SegmentDirectMemoryLZ4.remove(SegmentDirectMemoryLZ4.scala:199)
    at org.apache.donut.utils.logmap.ConcurrentLogHashMap.dealloc(ConcurrentLogHashMap.scala:271)
    at org.apache.donut.utils.logmap.ConcurrentLogHashMap.put(ConcurrentLogHashMap.scala:193)
    at org.apache.donut.memstore.MemStoreLogMap.put(MemStoreLogMap.scala:34)
    at net.imagini.dxp.graphstream.connectedbsp.ConnectedBSPProcessor.bootState(ConnectedBSPProcessor.scala:56)
    at net.imagini.dxp.graphstream.connectedbsp.ConnectedBSPProcessingUnit$$anon$1.handleMessage(ConnectedBSPProcessingUnit.scala:52)